### PR TITLE
Homepage with Structure Improvements and Feature Highlights

### PR DESCRIPTION
**Pull request by jagabomb**
**Updated PR**

[09 May 2024] Features section now includes Z-shaped reading layout pattern.
Screenshot 2024-05-09 at 10 49 32

[12 Feb 2024] Just rebased PR to include recent updates to the site logo replacement.

This PR implements the design mockup for the Trento Project homepage which highlights several features of Trento. There are a series of changes which affect use and structure of the **_index.html** file, the use of partials to create the homepage layout, a font weight fix, a navbar fix, basic mobile display support and supporting style changes. Below is an animated gif which shows the changes.

trento_project_new_homepage

**Initial Draft PR**

This PR replaces the hardcoded **index.html** template file with a stripped down version and serves **_index.md** as a content file for all sections on the homepage except the **hero** section. The hero section has been moved to a partial file which is included in the **index.html** template file. By having the hero file as a separate section it can span from edge to edge of the screen without being restricted to the with of the main content container.

Another change is the use of shortcodes to improve legibility and development of the future changes on the **_index.md** file. There are two proposed solutions. **Solution 1** (commented in the _index.md file) follows a similar approach to standard html coding by using wrapping/nesting shortcodes like the use of `divs`. Option 2 attempts to expose all related tags for each child element and instance (e.g. Image1, Title1, Caption1, Image2... etc).

Screenshot 2023-09-11 at 13 13 09

### CODE REVIEW

**Comment by stefanotorresi** [comment]
Thanks for this work, Jurgen.

In principle, I like the idea of extracting blocks into dedicated reusable shortcodes.
That said, I'm not so sure about using them in the context of the index page: the whole point of markdown is that it is supposed to make the source files readable as they are, in raw form.
Adding shortcodes to a markdown file basically turns it into a custom dialect that is as usable as HTML (at best) so, at that point, you might as well just use an HTML partial.

You can better see what I mean by comparing how the "About" page source file looks:
https://github.com/trento-project/trento-project.github.io/blob/f322df90b53a18122249d416fd7b0331b3f748c4/content/about/index.md
compared the Index page:
https://github.com/trento-project/trento-project.github.io/blob/f322df90b53a18122249d416fd7b0331b3f748c4/content/_index.md

As you can see, too many shortcodes in markdown kinda defeat its purpose. It's not black & white, though: it's very hard to strike the right balance.
What I see usually happening is that custom shortcodes are introduced in markdown as a last resort, when a partial is too hard to integrate in the layout and at the same time the limits of markdown's simplicity have been reached.

What I would suggest trying is either of the following:
- use a custom layout for the index page that includes a sub-partial for the horizontally distributed blocks before the actual markdown content, and backpedal on the shortcodes idea entirely;
- simplify the shortcode (I liked option 1 more, by the way) so that it doesn't compromise the markdown legibility (either by hard coding the parameters in the shortcode source template, which is a bit of a wonky solution, or by extracting the parameters in the "[front-matter](https://gohugo.io/content-management/front-matter/)" of the markdown, effectively making them page parameters, which would make them nicely contained in a markdown table format, at the top of the page).

**Comment by jagabomb** [comment]
@stefanotorresi thanks for your feedback. I will investigate the two directions to see which direction could work better. In essence, I would like to retain the legibility that markdown brings without obscuring it with shortcodes or HTML. I think I have been more focused on the re-usable component feature of shortcodes but I will see what I can achieve with sub-partials.

**Comment by stefanotorresi** [comment]
Looks very good! Carry on as intended to remove the draft status.

**Comment by stefanotorresi** [comment]
This is solid, Jurgen. I'm gonna work on the copy and keep adding commits to the same branch.

**Pull request merged**
