### PR TITLE
add a docs page with a collection of links

### PR DESCRIPTION
**Pull request by stefanotorresi**
I don't like it that much but better than nothing.
Screenshot 2024-06-27 143428

### CODE REVIEW

**Review by arbulu89 — APPROVED** [review]
LGTM.
I would maybe include `trento-ansible` link somewhere as it is not referenced anywhere else otherwise

**Review by jagabomb — APPROVED** [review]
LGTM

**Comment by jagabomb** [comment]
@stefanotorresi Should we also update the **Get Started with Trento** section on the homepage with the Docs page as per this PR?

Below is an image of the section that I am referring.
Screenshot 2024-06-28 at 14 05 05

**Comment by stefanotorresi** [comment]
> @stefanotorresi Should we also update the **Get Started with Trento** section on the homepage with the Docs page as per this PR?

Yes, that link is changed in this very PR and will point to the new page.

**Pull request merged**
