### PR TITLE
Added summary image to announcement post

### PR DESCRIPTION
**Pull request by jagabomb**
Added the right reference to replace default blog image with custom thumbnail for this post.

Screenshot 2023-08-08 at 14 09 04

### CODE REVIEW

**Review by nelsonkopliku — APPROVED** [review]
LGTM :eyes:

**Review by abravosuse — COMMENTED** [review]
I don't understand this PR @jagabomb . It references Trento 2.0.0.

**Comment by jagabomb** [comment]
> I don't understand this PR @jagabomb . It references Trento 2.0.0.

As discussed, this is just an enhancement on the previous post (**v2.0.0**) to remove the default castle placeholder image. Since we are going to have many announcements and it would be nice to visually differentiate each one.

**Comment by jagabomb** [comment]
Closing this in preparation for the announcement v2.1.0 post.

**Pull request merged**
