### PR TITLE
Docs View and Structure Changes to Improve UX

### PR DESCRIPTION
**Pull request by jagabomb**
This PR adds changes to enable the Docs section be a better repository of information. A side menu navigation was added to allow for sections and sub pages. This side menu was also tested across some responsive viewports. The main content for the documentation is placed on the right has side of the screen. This main section also retains the footer for the website so that there is always consistency of having the footer at the bottom of the page.

As discussed before, this PR is just to enable the Documentation section to be able to **accommodate more pages and sections** so that we can have a better overall experience when it comes to reviewing the Trento Documentation in a single destination. Currently Trento Documentation is split across multiple repositories and web articles which tend to be outdated while development is moving at a fast pace. In future PRs the team could add more pages which address topics like What is Trento?, How to get started with Trento, What is Trento Wanda?, What are Checks, etc...

**Overall changes to the website layout**
ezgif-2-b0267a0040

**Tablet View with Collapsed Side Bar Menu**
Screenshot 2024-07-15 at 12 17 32

**Tablet View with Expanded Side Bar Menu**
Screenshot 2024-07-15 at 12 17 47

**Example of Subpage**
Screenshot 2024-07-15 at 12 20 32

**Ability to add Sub Sections to the Main Menu**
Screenshot 2024-07-15 at 12 37 04

### CODE REVIEW

**Review by stefanotorresi — CHANGES_REQUESTED** [review]
Hey Jurgen, I like this, I think it's going in the direction we want.

The only remark I have for now is the behavior of the dark footer block: shouldn't it go 100% wide and not be overlapped by the navigation bar?

Something like this:
Screenshot 2024-07-15 133352

**Comment by jagabomb** [comment]
@stefanotorresi Below is an example of what is possible if we treat the window as a single view (having the footer at the bottom with a single scrollbar for both sidebar and main panels). The tradeoff with this approach, is that there is only one single scroll bar for all content in the window. So there is a better UI structure consistency but there is also a minor UX limitation if the sidebar content is much shorter than the post. Would you prefer this implementation?

**Example of Sidebar with Short Content**
ezgif-5-da69d25046

**Example of Sidebar with Long Content**
ezgif-2-9f039d0c31

**Comment by stefanotorresi** [comment]
@jagabomb yes, let's go with this approach, soon enough we'll have enough items in the side nav anyway.

**Comment by jagabomb** [comment]
@stefanotorresi The changes have been made. Here are a couple of examples of the changes.

**Desktop View**
Trento-Project---Documentation1-ezgif com-video-to-gif-converter

**Tablet (Responsive) View**
Trento-Project---Documentation2-ezgif com-video-to-gif-converter

**Review by stefanotorresi — APPROVED** [review]

**Pull request merged**
